FROM node:21-alpine
WORKDIR /home/node/app/request-generator

ARG VITE_URL
ENV VITE_URL=$VITE_URL

COPY --chown=node:node . .
RUN npm install
EXPOSE 3000
EXPOSE 3001

HEALTHCHECK --interval=30s --start-period=15s --timeout=10m --retries=10 CMD wget --no-verbose --tries=1 --spider ${VITE_URL} || exit 1

CMD ./dockerRunnerDev.sh
